### ISSUE TITLE
Kabanboard setup for final capstone

### ISSUE THREAD

**Issue by PromzzyKoncepts** [PromzzyKoncepts/Book-Appointment-App#13]
# Hey There:

This group is a team of 3 developers as follows: @PromzzyKoncepts @ndikumanaisaie @Abdullah2213565 

Here is a [link to the kabanboard](https://github.com/PromzzyKoncepts/Book-Appointment-App/projects/1)
![image](https://user-images.githubusercontent.com/69632681/228828907-ff866fe3-5a01-4b02-b6d6-d9e957565824.png)

### Kindly Review

**Comment by mcrd25** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your board.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the current state of the Kanban Board at the time of review request which is seen as a requirement [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Highlights
- You've met all requirements 👍 

## Optional suggestions
- [OPTIONAL] Consider adding labels to help identify and filter by different types of tasks/issues

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
